


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_db
    username: root
    password: Radagon.87
    port: 8080

  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: none
    hibernate:
      ddl-auto: update
    show-sql: true


  #spring.jpa.properties.hibernate.transaction.jta.platform = none
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: alujan.paellasoft@gmail.com
    password: phcr wvhn mhpv noue

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

openai:
  model: gpt-3.5-turbo-0125
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions

